/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import config.KoneksiDatabase;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import javax.swing.JTextField;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.Connection;

/**
 *
 * @author gungwira
 */
public class LoginPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;

        initComponents();

        setSize(1280, 754);

        // STYLING USERNAME & PASSWORD INPUT
        styleInput(usernameInput, "Masukkan username...");
        styleInput(passwordInput, "Masukkan password...");

        // CEGAH WARNA BUTTON MENJADI TRANSPARAN
        loginButton.setOpaque(true);

        // KETIKA OPSI BUAT AKUN DITEKAN
        createAccountLink.setCursor(new Cursor(Cursor.HAND_CURSOR));
        createAccountLink.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainFrame.showRegister();
            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createAccountLink.setForeground(new java.awt.Color(0, 102, 51));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createAccountLink.setForeground(new java.awt.Color(51, 51, 51));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        usernameInput = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordInput = new javax.swing.JTextField();
        termsCheckbox = new javax.swing.JCheckBox();
        loginButton = new javax.swing.JButton();
        createAccountLink = new javax.swing.JLabel();
        image = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Heiti SC", 1, 36)); // NOI18N
        title.setText("Selamat Datang");
        title.setToolTipText("");
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        description.setFont(new java.awt.Font("Heiti SC", 1, 16)); // NOI18N
        description.setForeground(new java.awt.Color(102, 102, 102));
        description.setText("Silahkan login terlebih dahulu untuk masuk ke sistem");
        description.setToolTipText("");
        add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        usernameLabel.setFont(new java.awt.Font("Heiti SC", 1, 16)); // NOI18N
        usernameLabel.setText("Username");
        usernameLabel.setToolTipText("");
        add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        usernameInput.setFont(new java.awt.Font("Heiti SC", 0, 16)); // NOI18N
        usernameInput.setForeground(new java.awt.Color(102, 102, 102));
        usernameInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        usernameInput.setMargin(new java.awt.Insets(2, 20, 2, 20));
        usernameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameInputActionPerformed(evt);
            }
        });
        add(usernameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 400, 40));

        passwordLabel.setFont(new java.awt.Font("Heiti SC", 1, 16)); // NOI18N
        passwordLabel.setText("Password");
        passwordLabel.setToolTipText("");
        add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        passwordInput.setFont(new java.awt.Font("Heiti SC", 0, 16)); // NOI18N
        passwordInput.setForeground(new java.awt.Color(102, 102, 102));
        passwordInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        passwordInput.setMargin(new java.awt.Insets(20, 20, 20, 20));
        passwordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordInputActionPerformed(evt);
            }
        });
        add(passwordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 400, 40));

        termsCheckbox.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        termsCheckbox.setForeground(new java.awt.Color(51, 51, 51));
        termsCheckbox.setText("Saya setuju dengan berbagai syarat & ketentuan");
        termsCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termsCheckboxActionPerformed(evt);
            }
        });
        add(termsCheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 400, -1));

        loginButton.setBackground(new java.awt.Color(0, 51, 51));
        loginButton.setFont(new java.awt.Font("Heiti SC", 1, 16)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login Sekarang");
        loginButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 400, 50));

        createAccountLink.setFont(new java.awt.Font("Heiti SC", 0, 16)); // NOI18N
        createAccountLink.setForeground(new java.awt.Color(51, 51, 51));
        createAccountLink.setText("<html>Belum punya akun? <span style=\"text-decoration: underline;\">Buat akun sekarang</span></html>");
        add(createAccountLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 560, -1, -1));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/login_img.png"))); // NOI18N
        image.setIconTextGap(0);
        add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 640, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void usernameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameInputActionPerformed

    private void passwordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordInputActionPerformed

    private void termsCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termsCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_termsCheckboxActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String username = usernameInput.getText();
        String password = passwordInput.getText();

        if (username.equals("") || username.equals("Masukkan username...") || password.equals("") || password.equals("Masukkan password...")) {
            System.out.println("Pastikan setiap kolom terisi");
            return;
        }

        try {
            Connection c = KoneksiDatabase.getKoneksi();
            String sql = "SELECT * FROM users WHERE username = ? AND password = ?";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, username);
            p.setString(2, password);
            ResultSet r = p.executeQuery();
            
            if (r.next()) {
            // User ditemukan
            int id = r.getInt("id");
            String uname = r.getString("username");

            System.out.println("LOGIN BERHASIL");
                    
            usernameInput.setText("");
            passwordInput.setText("");

            } else {
                // User tidak ditemukan
                System.out.println("Login gagal! Username atau password salah.");
            }

            r.close();
            p.close();           

        } catch (SQLException e) {
            System.out.println("Terjadi kesalahan : " + e);
        }
    }//GEN-LAST:event_loginButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel createAccountLink;
    private javax.swing.JLabel description;
    private javax.swing.JLabel image;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField passwordInput;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JCheckBox termsCheckbox;
    private javax.swing.JLabel title;
    private javax.swing.JTextField usernameInput;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables

    private void addPlaceholder(JTextField field, String placeholder) {
        field.setForeground(new java.awt.Color(150, 150, 150));
        field.setText(placeholder);

        field.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (field.getText().equals(placeholder)) {
                    field.setText("");
                    field.setForeground(new java.awt.Color(0, 0, 0));
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (field.getText().isEmpty()) {
                    field.setForeground(new java.awt.Color(150, 150, 150));
                    field.setText(placeholder);
                }
            }
        });
    }

    private void styleInput(JTextField field, String placeholder) {
        addPlaceholder(field, placeholder);

        field.setBorder(
                javax.swing.BorderFactory.createCompoundBorder(
                        javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 1, true),
                        javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15)
                )
        );
    }
}
