/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import javax.swing.JTextField;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.Connection;

import config.KoneksiDatabase;

/**
 *
 * @author gungwira
 */
public class RegisterPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;

    /**
     * Creates new form RegisterPanel
     */
    public RegisterPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;

        initComponents();

        setSize(1280, 754);

        // STYLING USERNAME & PASSWORD INPUT
        styleInput(usernameInput, "Masukkan username...");
        styleInput(passwordInput, "Masukkan password...");
        styleInput(passwordConfirmInput, "Konfirmasi Password...");

        // CEGAH WARNA BUTTON MENJADI TRANSPARAN
        registerButton.setOpaque(true);

        // KETIKA OPSI BUAT AKUN DITEKAN
        LoginLink.setCursor(new Cursor(Cursor.HAND_CURSOR));
        LoginLink.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainFrame.showLogin();
            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginLink.setForeground(new java.awt.Color(0, 102, 51));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginLink.setForeground(new java.awt.Color(51, 51, 51));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        description = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        usernameInput = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordInput = new javax.swing.JTextField();
        passwordLabel1 = new javax.swing.JLabel();
        passwordConfirmInput = new javax.swing.JTextField();
        termsCheckbox = new javax.swing.JCheckBox();
        registerButton = new javax.swing.JButton();
        LoginLink = new javax.swing.JLabel();
        image = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        description.setFont(new java.awt.Font("Heiti SC", 1, 16)); // NOI18N
        description.setForeground(new java.awt.Color(102, 102, 102));
        description.setText("Buat akun Anda untuk melanjutkan proses sistem");
        description.setToolTipText("");
        add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        title.setFont(new java.awt.Font("Heiti SC", 1, 36)); // NOI18N
        title.setText("Buat Akun");
        title.setToolTipText("");
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        usernameLabel.setFont(new java.awt.Font("Heiti SC", 1, 16)); // NOI18N
        usernameLabel.setText("Username");
        usernameLabel.setToolTipText("");
        add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        usernameInput.setFont(new java.awt.Font("Heiti SC", 0, 16)); // NOI18N
        usernameInput.setForeground(new java.awt.Color(102, 102, 102));
        usernameInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        usernameInput.setMargin(new java.awt.Insets(2, 20, 2, 20));
        usernameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameInputActionPerformed(evt);
            }
        });
        add(usernameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 400, 40));

        passwordLabel.setFont(new java.awt.Font("Heiti SC", 1, 16)); // NOI18N
        passwordLabel.setText("Password");
        passwordLabel.setToolTipText("");
        add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        passwordInput.setFont(new java.awt.Font("Heiti SC", 0, 16)); // NOI18N
        passwordInput.setForeground(new java.awt.Color(102, 102, 102));
        passwordInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        passwordInput.setMargin(new java.awt.Insets(20, 20, 20, 20));
        passwordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordInputActionPerformed(evt);
            }
        });
        add(passwordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 400, 40));

        passwordLabel1.setFont(new java.awt.Font("Heiti SC", 1, 16)); // NOI18N
        passwordLabel1.setText("Konfirmasi Password");
        passwordLabel1.setToolTipText("");
        add(passwordLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        passwordConfirmInput.setFont(new java.awt.Font("Heiti SC", 0, 16)); // NOI18N
        passwordConfirmInput.setForeground(new java.awt.Color(102, 102, 102));
        passwordConfirmInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        passwordConfirmInput.setMargin(new java.awt.Insets(20, 20, 20, 20));
        passwordConfirmInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordConfirmInputActionPerformed(evt);
            }
        });
        add(passwordConfirmInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 400, 40));

        termsCheckbox.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        termsCheckbox.setForeground(new java.awt.Color(51, 51, 51));
        termsCheckbox.setText("Saya setuju dengan berbagai syarat & ketentuan");
        termsCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termsCheckboxActionPerformed(evt);
            }
        });
        add(termsCheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 400, -1));

        registerButton.setBackground(new java.awt.Color(0, 51, 51));
        registerButton.setFont(new java.awt.Font("Heiti SC", 1, 16)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Buat Akun");
        registerButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 400, 50));

        LoginLink.setFont(new java.awt.Font("Heiti SC", 0, 16)); // NOI18N
        LoginLink.setForeground(new java.awt.Color(51, 51, 51));
        LoginLink.setText("<html>Sudah punya akun? <span style=\"text-decoration: underline;\">Login sekarang</span></html>");
        add(LoginLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 650, -1, -1));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/login_img.png"))); // NOI18N
        image.setIconTextGap(0);
        add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 640, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void usernameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameInputActionPerformed

    private void passwordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordInputActionPerformed

    private void passwordConfirmInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordConfirmInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordConfirmInputActionPerformed

    private void termsCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termsCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_termsCheckboxActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        String username = usernameInput.getText();
        String password = passwordInput.getText();
        String confirmPassword = passwordConfirmInput.getText();
        
        if(username.equals("") || password.equals("") || confirmPassword.equals("") || username.equals("Masukkan username...") || password.equals("Masukkan password...") || confirmPassword.equals("Konfirmasi Password...")){
            System.out.println("Pastikan semua data terisi");
            return;
        }
        
        if(!password.equals(confirmPassword)){
            System.out.println("Password dan konfirmasi password tidak sama");
            return;
        }
        
        try{
            Connection c = KoneksiDatabase.getKoneksi();
            String sql = "INSERT INTO users (username, password) VALUES (?, ?)";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, username);
            p.setString(2, password);
            p.executeUpdate();
            p.close();
            
            usernameInput.setText("");
            passwordInput.setText("");
            passwordConfirmInput.setText("");
            
            
        }catch(SQLException e){
            System.out.println("Terjadi kesalahan : " + e);
        }
        
    }//GEN-LAST:event_registerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoginLink;
    private javax.swing.JLabel description;
    private javax.swing.JLabel image;
    private javax.swing.JTextField passwordConfirmInput;
    private javax.swing.JTextField passwordInput;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel passwordLabel1;
    private javax.swing.JButton registerButton;
    private javax.swing.JCheckBox termsCheckbox;
    private javax.swing.JLabel title;
    private javax.swing.JTextField usernameInput;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables

    private void addPlaceholder(JTextField field, String placeholder) {
        field.setForeground(new java.awt.Color(150, 150, 150));
        field.setText(placeholder);

        field.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (field.getText().equals(placeholder)) {
                    field.setText("");
                    field.setForeground(new java.awt.Color(0, 0, 0));
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (field.getText().isEmpty()) {
                    field.setForeground(new java.awt.Color(150, 150, 150));
                    field.setText(placeholder);
                }
            }
        });
    }

    private void styleInput(JTextField field, String placeholder) {
        addPlaceholder(field, placeholder);

        field.setBorder(
                javax.swing.BorderFactory.createCompoundBorder(
                        javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 1, true),
                        javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15)
                )
        );
    }
}
