/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.dashboard;

import model.Court;

/**
 *
 * @author gungwira
 */
public class CourtDetailPanel extends javax.swing.JPanel {
    private DashboardFrame dashboardFrame;
    private Court selectedCourt;

    /**
     * Creates new form CourtDetailPanel
     */
    public CourtDetailPanel(DashboardFrame dashboardFrame) {
        this.dashboardFrame = dashboardFrame;

        initComponents();

        setSize(1280, 754);
    }
    
    public void setCourt(Court court){
        this.selectedCourt = court;
        
        courtDetailTitle.setText("Lapangan " + selectedCourt.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        sidebarLogo = new javax.swing.JLabel();
        sidebarUsersButton = new javax.swing.JButton();
        SidebarLogoSeperator = new javax.swing.JPanel();
        sidebarDashboardButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        courtDetailTitle = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(234, 234, 234));
        setSize(new java.awt.Dimension(1280, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(14, 60, 61));
        sidebar.setForeground(new java.awt.Color(14, 60, 61));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebarLogo.setFont(new java.awt.Font("Heiti SC", 0, 16)); // NOI18N
        sidebarLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/boombinton_logo.png"))); // NOI18N
        sidebarLogo.setText("BoomBinton");
        sidebar.add(sidebarLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 180, 40));

        sidebarUsersButton.setBackground(new java.awt.Color(14, 60, 61));
        sidebarUsersButton.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        sidebarUsersButton.setForeground(new java.awt.Color(255, 255, 255));
        sidebarUsersButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/users-icon.png"))); // NOI18N
        sidebarUsersButton.setText(" Users");
        sidebarUsersButton.setBorder(null);
        sidebarUsersButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sidebarUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidebarUsersButtonActionPerformed(evt);
            }
        });
        sidebar.add(sidebarUsersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 180, 40));

        SidebarLogoSeperator.setBackground(new java.awt.Color(20, 85, 87));

        javax.swing.GroupLayout SidebarLogoSeperatorLayout = new javax.swing.GroupLayout(SidebarLogoSeperator);
        SidebarLogoSeperator.setLayout(SidebarLogoSeperatorLayout);
        SidebarLogoSeperatorLayout.setHorizontalGroup(
            SidebarLogoSeperatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        SidebarLogoSeperatorLayout.setVerticalGroup(
            SidebarLogoSeperatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        sidebar.add(SidebarLogoSeperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 180, 1));

        sidebarDashboardButton.setBackground(new java.awt.Color(14, 60, 61));
        sidebarDashboardButton.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        sidebarDashboardButton.setForeground(new java.awt.Color(255, 255, 255));
        sidebarDashboardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/dashboard-icon.png"))); // NOI18N
        sidebarDashboardButton.setText(" Dashboard");
        sidebarDashboardButton.setBorder(null);
        sidebarDashboardButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sidebarDashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidebarDashboardButtonActionPerformed(evt);
            }
        });
        sidebar.add(sidebarDashboardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 180, 40));

        jLabel6.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Admin Dashboard");
        sidebar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 720));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        courtDetailTitle.setFont(new java.awt.Font("Heiti SC", 0, 24)); // NOI18N
        courtDetailTitle.setText("Lapangan A");
        header.add(courtDetailTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Pilih jam sewa yang ingin dibooking");
        header.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 65, -1, -1));

        add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 1060, 110));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Heiti SC", 0, 20)); // NOI18N
        jLabel5.setText("Rabu, 3 Desember 2025");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Jam tersedia : 8/12");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jButton4.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jButton4.setText("08.00 - 09.00");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 210, 60));

        jButton6.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jButton6.setText("08.00 - 09.00");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 100, 210, 60));

        jButton7.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jButton7.setText("08.00 - 09.00");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 210, 60));

        jButton8.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jButton8.setText("08.00 - 09.00");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 170, 210, 60));

        jButton5.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jButton5.setText("08.00 - 09.00");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 210, 60));

        jButton9.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jButton9.setText("08.00 - 09.00");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 210, 60));

        jButton10.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jButton10.setText("08.00 - 09.00");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 210, 60));

        jButton11.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jButton11.setText("08.00 - 09.00");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 240, 210, 60));

        jButton12.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jButton12.setText("08.00 - 09.00");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 210, 60));

        jButton13.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jButton13.setText("08.00 - 09.00");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 210, 60));

        jButton14.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jButton14.setText("08.00 - 09.00");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 310, 210, 60));

        jButton15.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jButton15.setText("08.00 - 09.00");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 210, 60));

        jButton16.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jButton16.setText("08.00 - 09.00");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 210, 60));

        jButton17.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jButton17.setText("08.00 - 09.00");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 380, 210, 60));

        jButton18.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jButton18.setText("08.00 - 09.00");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 210, 60));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 730, 560));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Detail pesanan");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel9.setFont(new java.awt.Font("Heiti SC", 0, 20)); // NOI18N
        jLabel9.setText("Ringkasan Pesanan");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jButton1.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jButton1.setText("Konfirmasi");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 283, 190, 50));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 130, 250, 360));
    }// </editor-fold>//GEN-END:initComponents

    private void sidebarUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidebarUsersButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sidebarUsersButtonActionPerformed

    private void sidebarDashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidebarDashboardButtonActionPerformed
        dashboardFrame.showCourtPanel();
    }//GEN-LAST:event_sidebarDashboardButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SidebarLogoSeperator;
    private javax.swing.JLabel courtDetailTitle;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel sidebar;
    private javax.swing.JButton sidebarDashboardButton;
    private javax.swing.JLabel sidebarLogo;
    private javax.swing.JButton sidebarUsersButton;
    // End of variables declaration//GEN-END:variables
}
