/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.dashboard;

import controller.CourtController;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Court;

/**
 *
 * @author gungwira
 */
public class CourtPanel extends javax.swing.JPanel {

    private DashboardFrame dashboardFrame;
    private CourtController courtController;

    /**
     * Creates new form CourtPanel
     */
    public CourtPanel(DashboardFrame dashboardFrame) {
        this.dashboardFrame = dashboardFrame;
        courtController = new CourtController();

        initComponents();

        setSize(1280, 754);
        
//        gridContainer.setLayout(new GridLayout(0, 2, 20, 20));
    }

    public void setupPanel() {
        gridContainer.removeAll();

        List<Court> courts = courtController.getAllCourts();
        System.out.println("Jumlah court: " + courts.size());

        for (Court c : courts) {
            JPanel card = createCourtCard(
                    c.getName(),
                    "Rp " + c.getPrice_per_hour() + "/jam",
                    "Jadwal Bermain Tersedia",
                    "13,4m x 6,10m"
            );

            card.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent evt) {
                    Court selectedCourt = courtController.getCourtById(c.getId());
                    dashboardFrame.getCourtDetailPanel().setCourt(selectedCourt);
                    dashboardFrame.showCourtDetailPanel();
                }
            });

            gridContainer.add(card);

        }
        
        gridContainer.revalidate();
        gridContainer.repaint();
    }

    public JPanel createCourtCard(String name, String price, String slotInfo, String size) {

        JPanel card = new JPanel();
        card.setPreferredSize(new java.awt.Dimension(490, 170));
        card.setBackground(Color.WHITE);
        card.setLayout(null);

        // Label Nama Lapangan
        JLabel lblName = new JLabel(name);
        lblName.setFont(new java.awt.Font("Heiti SC", 0, 24));
        card.add(lblName);
        lblName.setBounds(30, 30, 200, 30);

        // Label Slot
        JLabel lblSlot = new JLabel(slotInfo);
        lblSlot.setFont(new java.awt.Font("Heiti SC", 0, 14));
        lblSlot.setForeground(new Color(102, 102, 102));
        lblSlot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/check_icon.png")));
        card.add(lblSlot);
        lblSlot.setBounds(30, 125, 200, 20);

        // Label Ukuran
        JLabel lblSize = new JLabel("Ukuran : " + size);
        lblSize.setFont(new java.awt.Font("Heiti SC", 0, 14));
        lblSize.setForeground(new Color(102, 102, 102));
        card.add(lblSize);
        lblSize.setBounds(30, 70, 250, 20);

        // Label Harga
        JLabel lblPrice = new JLabel(price);
        lblPrice.setFont(new java.awt.Font("Heiti SC", 0, 14));
        lblPrice.setForeground(Color.WHITE);
        card.add(lblPrice);
        lblPrice.setBounds(353, 33, 150, 25);

        // Background harga
        JLabel lblPriceBg = new JLabel(new javax.swing.ImageIcon(
                getClass().getResource("/assets/images/button_dashboard_bg.png")
        ));
        card.add(lblPriceBg);
        lblPriceBg.setBounds(340, 20, 120, 50);

        // Icon pojok kanan bawah
        JLabel cornerIcon = new JLabel(new javax.swing.ImageIcon(
                getClass().getResource("/assets/images/corner-icon.png")
        ));
        card.add(cornerIcon);
        cornerIcon.setBounds(430, 115, 40, 40);

        return card;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        sidebarLogo = new javax.swing.JLabel();
        sidebarUsersButton = new javax.swing.JButton();
        SidebarLogoSeperator = new javax.swing.JPanel();
        sidebarDashboardButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        sidebarUsersButton1 = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        gridContainer = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(237, 237, 237));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(14, 60, 61));
        sidebar.setForeground(new java.awt.Color(14, 60, 61));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebarLogo.setFont(new java.awt.Font("Heiti SC", 0, 16)); // NOI18N
        sidebarLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/boombinton_logo.png"))); // NOI18N
        sidebarLogo.setText("BoomBinton");
        sidebar.add(sidebarLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 180, 40));

        sidebarUsersButton.setBackground(new java.awt.Color(14, 60, 61));
        sidebarUsersButton.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        sidebarUsersButton.setForeground(new java.awt.Color(255, 255, 255));
        sidebarUsersButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/users-icon.png"))); // NOI18N
        sidebarUsersButton.setText(" Users");
        sidebarUsersButton.setBorder(null);
        sidebarUsersButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sidebarUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidebarUsersButtonActionPerformed(evt);
            }
        });
        sidebar.add(sidebarUsersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 180, 40));

        SidebarLogoSeperator.setBackground(new java.awt.Color(20, 85, 87));

        javax.swing.GroupLayout SidebarLogoSeperatorLayout = new javax.swing.GroupLayout(SidebarLogoSeperator);
        SidebarLogoSeperator.setLayout(SidebarLogoSeperatorLayout);
        SidebarLogoSeperatorLayout.setHorizontalGroup(
            SidebarLogoSeperatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        SidebarLogoSeperatorLayout.setVerticalGroup(
            SidebarLogoSeperatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        sidebar.add(SidebarLogoSeperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 180, 1));

        sidebarDashboardButton.setBackground(new java.awt.Color(14, 60, 61));
        sidebarDashboardButton.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        sidebarDashboardButton.setForeground(new java.awt.Color(255, 255, 255));
        sidebarDashboardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/dashboard-icon.png"))); // NOI18N
        sidebarDashboardButton.setText(" Dashboard");
        sidebarDashboardButton.setBorder(null);
        sidebarDashboardButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sidebarDashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidebarDashboardButtonActionPerformed(evt);
            }
        });
        sidebar.add(sidebarDashboardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 180, 40));

        jLabel6.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Admin Dashboard");
        sidebar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        sidebarUsersButton1.setBackground(new java.awt.Color(14, 60, 61));
        sidebarUsersButton1.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        sidebarUsersButton1.setForeground(new java.awt.Color(255, 255, 255));
        sidebarUsersButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/court-icon.png"))); // NOI18N
        sidebarUsersButton1.setText(" Court");
        sidebarUsersButton1.setBorder(null);
        sidebarUsersButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sidebarUsersButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidebarUsersButton1ActionPerformed(evt);
            }
        });
        sidebar.add(sidebarUsersButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 215, 180, 40));

        add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 720));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Pilih lapangan untuk memulai transaksi booking");
        header.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Heiti SC", 0, 24)); // NOI18N
        jLabel5.setText("Overview Lapangan");
        header.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 1060, 110));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 100, 0));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/Rental Lapangan Mudah 1.png"))); // NOI18N
        jPanel8.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1000, 250));

        jLabel7.setFont(new java.awt.Font("Heiti SC", 0, 20)); // NOI18N
        jLabel7.setText("Lapangan tersedia");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, -1, 50));

        gridContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 100, 0));
        gridContainer.setMinimumSize(new java.awt.Dimension(0, 0));
        gridContainer.setPreferredSize(new java.awt.Dimension(0, 0));
        gridContainer.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 20));
        jPanel8.add(gridContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 1040, 130));

        jScrollPane1.setViewportView(jPanel8);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 1060, 610));
    }// </editor-fold>//GEN-END:initComponents

    private void sidebarUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidebarUsersButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sidebarUsersButtonActionPerformed

    private void sidebarDashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidebarDashboardButtonActionPerformed
        dashboardFrame.showCourtPanel();
    }//GEN-LAST:event_sidebarDashboardButtonActionPerformed

    private void sidebarUsersButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidebarUsersButton1ActionPerformed
        // TODO add your handling code here:
        dashboardFrame.showManageCourtPanel();
    }//GEN-LAST:event_sidebarUsersButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SidebarLogoSeperator;
    private javax.swing.JPanel gridContainer;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel sidebar;
    private javax.swing.JButton sidebarDashboardButton;
    private javax.swing.JLabel sidebarLogo;
    private javax.swing.JButton sidebarUsersButton;
    private javax.swing.JButton sidebarUsersButton1;
    // End of variables declaration//GEN-END:variables

}
