/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.dashboard;

import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author gungwira
 */
public class DashboardFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardFrame.class.getName());

    private CardLayout cardLayout;
    private JPanel mainPanel;
    private CourtPanel courtPanel;
    private CourtDetailPanel courtDetailPanel;
    private PaymentPanel paymentPanel;
    private ManageCourtPanel manageCourtPanel;
    /**
     * Creates new form DashboardFrame
     */
    public DashboardFrame() {        
        // Setup frame
        setTitle("BoomBinton");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(1280, 754);
        setLocationRelativeTo(null);
        
        // Setup CardLayout
        cardLayout = new CardLayout();
        mainPanel = new JPanel(cardLayout);
        
        // Buat panels
        courtPanel = new CourtPanel(this);
        courtDetailPanel = new CourtDetailPanel(this);
        paymentPanel = new PaymentPanel(this);
        manageCourtPanel = new ManageCourtPanel(this);
        
        // Tambahkan panels ke CardLayout dengan nama
        mainPanel.add(courtPanel, "court");
        mainPanel.add(courtDetailPanel, "courtDetail");
        mainPanel.add(paymentPanel, "payment");
        mainPanel.add(paymentPanel, "payment");
        mainPanel.add(manageCourtPanel, "manageCourt");
        
        // Tambahkan mainPanel ke frame
        add(mainPanel);
        
        // Tampilkan court panel dulu
        showCourtPanel();
//        showManageCourtPanel();
    }
    
    public void showCourtPanel(){
        cardLayout.show(mainPanel, "court");
    }
    
    public void showCourtDetailPanel(){
        cardLayout.show(mainPanel, "courtDetail");
    }
    
    public CourtDetailPanel getCourtDetailPanel() {
        return courtDetailPanel;
    }
    
    public void showPaymentPanel(){
        cardLayout.show(mainPanel, "payment");
    }
    
    public PaymentPanel getPaymentPanel(){
        return paymentPanel;
    }
    
    public void showManageCourtPanel(){
        cardLayout.show(mainPanel, "manageCourt");
    }
    
    public ManageCourtPanel getManageCourtPanel(){
        return manageCourtPanel;
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
