/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.dashboard;

/**
 *
 * @author gungwira
 */
public class ManageCourtPanel extends javax.swing.JPanel {
    private DashboardFrame dashboardFrame;

    /**
     * Creates new form ManageCourtPanel
     */
    public ManageCourtPanel(DashboardFrame dashboardFrame) {
        this.dashboardFrame = dashboardFrame;
        
        initComponents();
        
        setSize(1280, 754);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        sidebarLogo = new javax.swing.JLabel();
        sidebarUsersButton = new javax.swing.JButton();
        SidebarLogoSeperator = new javax.swing.JPanel();
        sidebarDashboardButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        inputName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputPrice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        checkBoxAktif = new javax.swing.JCheckBox();
        buttonCreate = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        boxCourtItem = new javax.swing.JPanel();
        containerInnerItem = new javax.swing.JPanel();
        titleCourtItem = new javax.swing.JLabel();
        priceCourtItem = new javax.swing.JLabel();
        editCourtItem = new javax.swing.JButton();
        deleteCourtItem = new javax.swing.JButton();

        setBackground(new java.awt.Color(239, 239, 239));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(14, 60, 61));
        sidebar.setForeground(new java.awt.Color(14, 60, 61));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebarLogo.setFont(new java.awt.Font("Heiti SC", 0, 16)); // NOI18N
        sidebarLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/boombinton_logo.png"))); // NOI18N
        sidebarLogo.setText("BoomBinton");
        sidebar.add(sidebarLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 180, 40));

        sidebarUsersButton.setBackground(new java.awt.Color(14, 60, 61));
        sidebarUsersButton.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        sidebarUsersButton.setForeground(new java.awt.Color(255, 255, 255));
        sidebarUsersButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/users-icon.png"))); // NOI18N
        sidebarUsersButton.setText(" Users");
        sidebarUsersButton.setBorder(null);
        sidebarUsersButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sidebarUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidebarUsersButtonActionPerformed(evt);
            }
        });
        sidebar.add(sidebarUsersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 180, 40));

        SidebarLogoSeperator.setBackground(new java.awt.Color(20, 85, 87));

        javax.swing.GroupLayout SidebarLogoSeperatorLayout = new javax.swing.GroupLayout(SidebarLogoSeperator);
        SidebarLogoSeperator.setLayout(SidebarLogoSeperatorLayout);
        SidebarLogoSeperatorLayout.setHorizontalGroup(
            SidebarLogoSeperatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        SidebarLogoSeperatorLayout.setVerticalGroup(
            SidebarLogoSeperatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        sidebar.add(SidebarLogoSeperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 180, 1));

        sidebarDashboardButton.setBackground(new java.awt.Color(14, 60, 61));
        sidebarDashboardButton.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        sidebarDashboardButton.setForeground(new java.awt.Color(255, 255, 255));
        sidebarDashboardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/dashboard-icon.png"))); // NOI18N
        sidebarDashboardButton.setText(" Dashboard");
        sidebarDashboardButton.setBorder(null);
        sidebarDashboardButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sidebarDashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidebarDashboardButtonActionPerformed(evt);
            }
        });
        sidebar.add(sidebarDashboardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 180, 40));

        jLabel6.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Admin Dashboard");
        sidebar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 720));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Heiti SC", 0, 24)); // NOI18N
        jLabel7.setText("Manajemen Lapangan");
        header.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Kelola data lapangan disini");
        header.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 1060, 110));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputName.setBackground(new java.awt.Color(249, 249, 249));
        inputName.setFont(new java.awt.Font("Heiti SC", 0, 16)); // NOI18N
        inputName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 239, 239), 1, true));
        jPanel1.add(inputName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 95, 290, 40));

        jLabel4.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Nama lapangan");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        inputPrice.setBackground(new java.awt.Color(249, 249, 249));
        inputPrice.setFont(new java.awt.Font("Heiti SC", 0, 16)); // NOI18N
        inputPrice.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 239, 239), 1, true));
        jPanel1.add(inputPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 185, 290, 40));

        jLabel9.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Harga sewa");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        checkBoxAktif.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        checkBoxAktif.setForeground(new java.awt.Color(102, 102, 102));
        checkBoxAktif.setText("Aktifkan lapangan");
        checkBoxAktif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxAktifActionPerformed(evt);
            }
        });
        jPanel1.add(checkBoxAktif, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        buttonCreate.setBackground(new java.awt.Color(15, 61, 62));
        buttonCreate.setFont(new java.awt.Font("Heiti SC", 0, 16)); // NOI18N
        buttonCreate.setForeground(new java.awt.Color(255, 255, 255));
        buttonCreate.setText("Buat Lapangan");
        jPanel1.add(buttonCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 290, 50));

        jLabel10.setFont(new java.awt.Font("Heiti SC", 0, 20)); // NOI18N
        jLabel10.setText("Tambah Lapangan");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 350, 370));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Heiti SC", 0, 20)); // NOI18N
        jLabel5.setText("Data Lapangan");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jScrollPane1.setBorder(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 12));

        boxCourtItem.setBackground(new java.awt.Color(249, 249, 249));
        boxCourtItem.setBounds(new java.awt.Rectangle(20, 20, 0, 0));
        boxCourtItem.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 16));

        containerInnerItem.setBackground(new java.awt.Color(249, 249, 249));
        containerInnerItem.setLayout(new java.awt.GridLayout(1, 0, 40, 0));

        titleCourtItem.setFont(new java.awt.Font("Heiti SC", 0, 16)); // NOI18N
        titleCourtItem.setText("Lapangan A");
        containerInnerItem.add(titleCourtItem);

        priceCourtItem.setBackground(new java.awt.Color(79, 138, 107));
        priceCourtItem.setFont(new java.awt.Font("Heiti SC", 0, 16)); // NOI18N
        priceCourtItem.setForeground(new java.awt.Color(79, 138, 107));
        priceCourtItem.setText("Rp 50.000/jam");
        containerInnerItem.add(priceCourtItem);

        editCourtItem.setBackground(new java.awt.Color(79, 138, 107));
        editCourtItem.setForeground(new java.awt.Color(255, 255, 255));
        editCourtItem.setText("Edit");
        editCourtItem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        editCourtItem.setOpaque(true);
        editCourtItem.setPreferredSize(new java.awt.Dimension(72, 24));
        containerInnerItem.add(editCourtItem);

        deleteCourtItem.setBackground(new java.awt.Color(204, 0, 51));
        deleteCourtItem.setForeground(new java.awt.Color(255, 255, 255));
        deleteCourtItem.setText("Hapus");
        deleteCourtItem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        deleteCourtItem.setOpaque(true);
        deleteCourtItem.setPreferredSize(new java.awt.Dimension(72, 24));
        containerInnerItem.add(deleteCourtItem);

        boxCourtItem.add(containerInnerItem);

        jPanel3.add(boxCourtItem);

        jScrollPane1.setViewportView(jPanel3);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 640, 490));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 620, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void sidebarUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidebarUsersButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sidebarUsersButtonActionPerformed

    private void sidebarDashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidebarDashboardButtonActionPerformed
        dashboardFrame.showCourtPanel();
    }//GEN-LAST:event_sidebarDashboardButtonActionPerformed

    private void checkBoxAktifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxAktifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxAktifActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SidebarLogoSeperator;
    private javax.swing.JPanel boxCourtItem;
    private javax.swing.JButton buttonCreate;
    private javax.swing.JCheckBox checkBoxAktif;
    private javax.swing.JPanel containerInnerItem;
    private javax.swing.JButton deleteCourtItem;
    private javax.swing.JButton editCourtItem;
    private javax.swing.JPanel header;
    private javax.swing.JTextField inputName;
    private javax.swing.JTextField inputPrice;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel priceCourtItem;
    private javax.swing.JPanel sidebar;
    private javax.swing.JButton sidebarDashboardButton;
    private javax.swing.JLabel sidebarLogo;
    private javax.swing.JButton sidebarUsersButton;
    private javax.swing.JLabel titleCourtItem;
    // End of variables declaration//GEN-END:variables
}
