/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.dashboard;

import controller.BookingController;
import controller.MemberController;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import model.Court;
import model.TimeSlot;
import model.Booking;
import model.Racket;
import model.Shuttlecock;
import util.ReceiptPdfUtil;

/**
 *
 * @author gungwira
 */
public class PaymentPanel extends javax.swing.JPanel {

    private DashboardFrame dashboardFrame;
    private Integer racketAmountVar;
    private Integer kokAmountVar;
    private Court court;
    private List<TimeSlot> selectedSlots = new ArrayList<>();
    private LocalDate date;
    private Integer totalOrder;
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("EEEE, d MMMM yyyy", new Locale("id", "ID"));
    private BookingController bookingController;
    private MemberController memberController;

    /**
     * Creates new form PaymentPanel
     */
    public PaymentPanel(DashboardFrame dashboardFrame) {
        this.dashboardFrame = dashboardFrame;
        this.racketAmountVar = 0;
        this.kokAmountVar = 0;
        this.totalOrder = 0;
        this.bookingController = new BookingController();
        this.memberController = new MemberController();

        initComponents();

        setSize(1280, 754);
    }

    public void setupData(Court court, List<TimeSlot> slots, LocalDate date) {
        this.court = court;
        this.selectedSlots = slots;
        this.date = date;

        setupPanel();
    }

    public void setupPanel() {
        detailCourtTitle.setText("Lapangan " + court.getName());
        dateOrder.setText(date.format(formatter));
        confirmButton.setOpaque(true);

        setupOrders();

    }

    public void setupOrders() {
        StringBuilder sbSlot = new StringBuilder();
        StringBuilder sbPrice = new StringBuilder();

        for (TimeSlot slot : selectedSlots) {
            sbSlot.append(slot.getStart_time())
                    .append(" - ")
                    .append(slot.getEnd_time())
                    .append("\n\n");

            sbPrice.append("Rp ")
                    .append(court.getPrice_per_hour().toString())
                    .append("\n\n");

            totalOrder += court.getPrice_per_hour();
        }

        grandTotalPrice.setText("Rp " + totalOrder);

        bookingTimes.setText("<html>" + sbSlot.toString().replace("\n", "<br>") + "</html>");
        bookingPrice.setText("<html>" + sbPrice.toString().replace("\n", "<br>") + "</html>");

    }

    public void updateOrder() {
        racketDetail.setText("Sewa Raket (" + racketAmountVar + ") :");
        kokDetail.setText("Beli Kok (" + kokAmountVar + ") :");

        racketPrice.setText("Rp " + racketAmountVar * 20000);
        kokPrice.setText("Rp " + kokAmountVar * 5000);

        grandTotalPrice.setText("Rp " + (totalOrder + racketAmountVar * 20000 + kokAmountVar * 5000));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        sidebarLogo = new javax.swing.JLabel();
        sidebarUsersButton = new javax.swing.JButton();
        SidebarLogoSeperator = new javax.swing.JPanel();
        sidebarDashboardButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        sidebarUsersButton1 = new javax.swing.JButton();
        sidebarUsersButton2 = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nameInput = new javax.swing.JTextField();
        phoneInput = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        racketInput = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        racketPlus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        racketMin = new javax.swing.JButton();
        racketAmount = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        kokInput = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        kokMin = new javax.swing.JButton();
        kokPlus = new javax.swing.JButton();
        kokAmount = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        grandTotalPrice = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        detailCourtTitle = new javax.swing.JLabel();
        kokDetail = new javax.swing.JLabel();
        dateOrder = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        kokPrice = new javax.swing.JLabel();
        racketDetail = new javax.swing.JLabel();
        racketPrice = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        bookingTimes = new javax.swing.JLabel();
        bookingPrice = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        grandTotalOrder = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(14, 60, 61));
        sidebar.setForeground(new java.awt.Color(14, 60, 61));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebarLogo.setFont(new java.awt.Font("Heiti SC", 0, 16)); // NOI18N
        sidebarLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/boombinton_logo.png"))); // NOI18N
        sidebarLogo.setText("BoomBinton");
        sidebar.add(sidebarLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 180, 40));

        sidebarUsersButton.setBackground(new java.awt.Color(14, 60, 61));
        sidebarUsersButton.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        sidebarUsersButton.setForeground(new java.awt.Color(255, 255, 255));
        sidebarUsersButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/users-icon.png"))); // NOI18N
        sidebarUsersButton.setText(" Member");
        sidebarUsersButton.setBorder(null);
        sidebarUsersButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sidebarUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidebarUsersButtonActionPerformed(evt);
            }
        });
        sidebar.add(sidebarUsersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 180, 40));

        SidebarLogoSeperator.setBackground(new java.awt.Color(20, 85, 87));

        javax.swing.GroupLayout SidebarLogoSeperatorLayout = new javax.swing.GroupLayout(SidebarLogoSeperator);
        SidebarLogoSeperator.setLayout(SidebarLogoSeperatorLayout);
        SidebarLogoSeperatorLayout.setHorizontalGroup(
            SidebarLogoSeperatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        SidebarLogoSeperatorLayout.setVerticalGroup(
            SidebarLogoSeperatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        sidebar.add(SidebarLogoSeperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 180, 1));

        sidebarDashboardButton.setBackground(new java.awt.Color(14, 60, 61));
        sidebarDashboardButton.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        sidebarDashboardButton.setForeground(new java.awt.Color(255, 255, 255));
        sidebarDashboardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/dashboard-icon.png"))); // NOI18N
        sidebarDashboardButton.setText(" Dashboard");
        sidebarDashboardButton.setBorder(null);
        sidebarDashboardButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sidebarDashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidebarDashboardButtonActionPerformed(evt);
            }
        });
        sidebar.add(sidebarDashboardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 180, 40));

        jLabel6.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Admin Dashboard");
        sidebar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        sidebarUsersButton1.setBackground(new java.awt.Color(14, 60, 61));
        sidebarUsersButton1.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        sidebarUsersButton1.setForeground(new java.awt.Color(255, 255, 255));
        sidebarUsersButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/court-icon.png"))); // NOI18N
        sidebarUsersButton1.setText(" Court");
        sidebarUsersButton1.setBorder(null);
        sidebarUsersButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sidebarUsersButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidebarUsersButton1ActionPerformed(evt);
            }
        });
        sidebar.add(sidebarUsersButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 215, 180, 40));

        sidebarUsersButton2.setBackground(new java.awt.Color(14, 60, 61));
        sidebarUsersButton2.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        sidebarUsersButton2.setForeground(new java.awt.Color(255, 255, 255));
        sidebarUsersButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/history boombin.png"))); // NOI18N
        sidebarUsersButton2.setText(" History");
        sidebarUsersButton2.setBorder(null);
        sidebarUsersButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sidebarUsersButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidebarUsersButton2ActionPerformed(evt);
            }
        });
        sidebar.add(sidebarUsersButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 180, 40));

        add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 720));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Heiti SC", 0, 24)); // NOI18N
        jLabel8.setText("Detail Pembayaran");
        header.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel17.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Silahkan selesaikan proses pembayaran disini");
        header.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 65, -1, -1));

        add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 1060, 110));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameInput.setFont(new java.awt.Font("Heiti SC", 0, 16)); // NOI18N
        nameInput.setForeground(new java.awt.Color(102, 102, 102));
        nameInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        nameInput.setMargin(new java.awt.Insets(2, 20, 2, 20));
        nameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInputActionPerformed(evt);
            }
        });
        jPanel2.add(nameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 540, 40));

        phoneInput.setFont(new java.awt.Font("Heiti SC", 0, 16)); // NOI18N
        phoneInput.setForeground(new java.awt.Color(102, 102, 102));
        phoneInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        phoneInput.setMargin(new java.awt.Insets(20, 20, 20, 20));
        phoneInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneInputActionPerformed(evt);
            }
        });
        jPanel2.add(phoneInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 540, 40));

        jLabel5.setFont(new java.awt.Font("Heiti SC", 0, 20)); // NOI18N
        jLabel5.setText("Detail Tambahan");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Nomor Telepon");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 175, -1, -1));

        racketInput.setBackground(new java.awt.Color(249, 249, 249));
        racketInput.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Rp 20.000/pcs");
        racketInput.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 45, -1, -1));

        jLabel13.setFont(new java.awt.Font("Heiti SC", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Sewa Raket");
        racketInput.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        racketPlus.setText("+");
        racketPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                racketPlusActionPerformed(evt);
            }
        });
        racketInput.add(racketPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 30, 50, -1));

        jPanel3.setBackground(new java.awt.Color(249, 249, 249));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        racketMin.setText("-");
        racketMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                racketMinActionPerformed(evt);
            }
        });
        jPanel3.add(racketMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        racketAmount.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        racketAmount.setText("0");
        jPanel3.add(racketAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 30, -1));

        racketInput.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 150, 30));

        jPanel2.add(racketInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 540, 80));

        jLabel12.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Nama pengguna");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 85, -1, -1));

        kokInput.setBackground(new java.awt.Color(249, 249, 249));
        kokInput.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Rp 10.000/pcs");
        kokInput.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 45, -1, -1));

        jLabel15.setFont(new java.awt.Font("Heiti SC", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Beli Kok");
        kokInput.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        kokMin.setText("-");
        kokMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kokMinActionPerformed(evt);
            }
        });
        kokInput.add(kokMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 50, -1));

        kokPlus.setText("+");
        kokPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kokPlusActionPerformed(evt);
            }
        });
        kokInput.add(kokPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 30, 50, -1));

        kokAmount.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        kokAmount.setText("0");
        kokInput.add(kokAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 30, -1));

        jPanel2.add(kokInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 540, 80));

        jLabel16.setFont(new java.awt.Font("Heiti SC", 0, 20)); // NOI18N
        jLabel16.setText("Detail Pembeli");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 35, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 610, 550));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Heiti SC", 0, 20)); // NOI18N
        jLabel11.setText("Detail Pesanan");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 35, -1, -1));

        grandTotalPrice.setFont(new java.awt.Font("Heiti SC", 0, 16)); // NOI18N
        grandTotalPrice.setForeground(new java.awt.Color(51, 51, 51));
        grandTotalPrice.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        grandTotalPrice.setText("Rp 0.000");
        jPanel1.add(grandTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 445, -1, -1));

        jScrollPane1.setBorder(null);

        jPanel6.setBackground(new java.awt.Color(249, 249, 249));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        detailCourtTitle.setFont(new java.awt.Font("Heiti SC", 0, 16)); // NOI18N
        detailCourtTitle.setForeground(new java.awt.Color(51, 51, 51));
        detailCourtTitle.setText("Lapangan A");
        jPanel6.add(detailCourtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        kokDetail.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        kokDetail.setForeground(new java.awt.Color(102, 102, 102));
        kokDetail.setText("Beli Kok (0) : ");
        jPanel6.add(kokDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        dateOrder.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        dateOrder.setForeground(new java.awt.Color(102, 102, 102));
        dateOrder.setText("Senin, 8 Desember 2025");
        jPanel6.add(dateOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel22.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Tambahan : ");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel26.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("Detail booking :");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        kokPrice.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        kokPrice.setForeground(new java.awt.Color(102, 102, 102));
        kokPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        kokPrice.setText("Rp 0.000");
        jPanel6.add(kokPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        racketDetail.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        racketDetail.setForeground(new java.awt.Color(102, 102, 102));
        racketDetail.setText("Sewa Raket (0) : ");
        jPanel6.add(racketDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        racketPrice.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        racketPrice.setForeground(new java.awt.Color(102, 102, 102));
        racketPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        racketPrice.setText("Rp 0.000");
        jPanel6.add(racketPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setToolTipText("");

        jPanel4.setBackground(new java.awt.Color(249, 249, 249));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookingTimes.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        bookingTimes.setForeground(new java.awt.Color(102, 102, 102));
        bookingTimes.setText("08:00 - 09:00");
        jPanel4.add(bookingTimes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        bookingPrice.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        bookingPrice.setForeground(new java.awt.Color(102, 102, 102));
        bookingPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bookingPrice.setText("Rp 0.000");
        jPanel4.add(bookingPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 150, -1));

        jScrollPane2.setViewportView(jPanel4);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 260, 100));

        jScrollPane1.setViewportView(jPanel6);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 300, 330));

        jLabel20.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Rincian pesanan penggunjung");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        grandTotalOrder.setFont(new java.awt.Font("Heiti SC", 0, 16)); // NOI18N
        grandTotalOrder.setForeground(new java.awt.Color(51, 51, 51));
        grandTotalOrder.setText("Total :");
        jPanel1.add(grandTotalOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 445, -1, -1));

        confirmButton.setBackground(new java.awt.Color(0, 51, 51));
        confirmButton.setFont(new java.awt.Font("Heiti SC", 1, 16)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmButton.setText("Konfirmasi");
        confirmButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        jPanel1.add(confirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 300, 50));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 130, 360, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void sidebarUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidebarUsersButtonActionPerformed
        // TODO add your handling code here:
        dashboardFrame.showMemberPanel();
    }//GEN-LAST:event_sidebarUsersButtonActionPerformed

    private void sidebarDashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidebarDashboardButtonActionPerformed
        dashboardFrame.showCourtPanel();
    }//GEN-LAST:event_sidebarDashboardButtonActionPerformed

    private void nameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameInputActionPerformed

    private void phoneInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneInputActionPerformed

    private void racketMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_racketMinActionPerformed
        // TODO add your handling code here:
        if (racketAmountVar != 0) {
            racketAmountVar--;
            racketAmount.setText(racketAmountVar.toString());
            updateOrder();
        }
    }//GEN-LAST:event_racketMinActionPerformed

    private void racketPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_racketPlusActionPerformed
        // TODO add your handling code here:
        racketAmountVar++;
        racketAmount.setText(racketAmountVar.toString());
        updateOrder();
    }//GEN-LAST:event_racketPlusActionPerformed

    private void kokMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kokMinActionPerformed
        // TODO add your handling code here:
        if (kokAmountVar != 0) {
            kokAmountVar--;
            kokAmount.setText(kokAmountVar.toString());
            updateOrder();
        }
    }//GEN-LAST:event_kokMinActionPerformed

    private void kokPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kokPlusActionPerformed
        // TODO add your handling code here:
        kokAmountVar++;
        kokAmount.setText(kokAmountVar.toString());
        updateOrder();
    }//GEN-LAST:event_kokPlusActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        String name = nameInput.getText();
        String phone = phoneInput.getText();

        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(
                    null,
                    "Nama pemesan tidak boleh kosong!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        if (phone.isEmpty()) {
            JOptionPane.showMessageDialog(
                    null,
                    "Nomor pemesan tidak boleh kosong!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        for (TimeSlot slot : selectedSlots) {
            Booking booking = new Booking(null, court.getId(), name, phone, slot.getId(), LocalDateTime.now(), court.getPrice_per_hour(), "Booked", LocalDateTime.now(), LocalDateTime.now());

            bookingController.addBooking(booking);
        }
        Racket racket = new Racket(racketAmountVar);
        Shuttlecock kok = new Shuttlecock(kokAmountVar);
        
        int points = (totalOrder + racketAmountVar * 20000 + kokAmountVar * 5000) / 10000;
        
        int currentPoints = memberController.handleMemberPoint(name, phone, points);
        
        JOptionPane.showMessageDialog(
                null,
                "Booking berhasil ditambahkan!",
                "Sukses",
                JOptionPane.INFORMATION_MESSAGE
        );
        ReceiptPdfUtil.generateReceipt(
                court,
                selectedSlots,
                date,
                name,
                phone,
                racket,
                kok,
                currentPoints
        );
        dashboardFrame.showCourtPanel();
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void sidebarUsersButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidebarUsersButton1ActionPerformed
        // TODO add your handling code here:
        dashboardFrame.showManageCourtPanel();
    }//GEN-LAST:event_sidebarUsersButton1ActionPerformed

    private void sidebarUsersButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidebarUsersButton2ActionPerformed
        // TODO add your handling code here:
        dashboardFrame.showHistoryPanel();
    }//GEN-LAST:event_sidebarUsersButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SidebarLogoSeperator;
    private javax.swing.JLabel bookingPrice;
    private javax.swing.JLabel bookingTimes;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel dateOrder;
    private javax.swing.JLabel detailCourtTitle;
    private javax.swing.JLabel grandTotalOrder;
    private javax.swing.JLabel grandTotalPrice;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel kokAmount;
    private javax.swing.JLabel kokDetail;
    private javax.swing.JPanel kokInput;
    private javax.swing.JButton kokMin;
    private javax.swing.JButton kokPlus;
    private javax.swing.JLabel kokPrice;
    private javax.swing.JTextField nameInput;
    private javax.swing.JTextField phoneInput;
    private javax.swing.JLabel racketAmount;
    private javax.swing.JLabel racketDetail;
    private javax.swing.JPanel racketInput;
    private javax.swing.JButton racketMin;
    private javax.swing.JButton racketPlus;
    private javax.swing.JLabel racketPrice;
    private javax.swing.JPanel sidebar;
    private javax.swing.JButton sidebarDashboardButton;
    private javax.swing.JLabel sidebarLogo;
    private javax.swing.JButton sidebarUsersButton;
    private javax.swing.JButton sidebarUsersButton1;
    private javax.swing.JButton sidebarUsersButton2;
    // End of variables declaration//GEN-END:variables
}
